# Generated by Django 5.0.7 on 2024-07-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings', '0001_initial'),
        ('products', '0008_alter_product_category_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_rating', to='Ratings.rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='products.product'),
        ),
    ]
